### 1. Generate README

# List all immediate directories at the root
dirs <- list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
dirs <- dirs[dirs != ""]  # Remove potential empty entries

# Start writing the README content
readme_lines <- c(
  "# Project Directory Index",
  "",
  "Welcome! This repository contains the following main directories:",
  "",
  "## Directories",
  ""
)

# Add a bullet list of links to each directory
dir_links <- paste0("- [", dirs, "/](./", dirs, "/)")
readme_lines <- c(readme_lines, dir_links)

# Optional: Add some nice footer
readme_lines <- c(
  readme_lines,
  "",
  "---",
  "",
  "Auto-generated by R."
)

# Write to README.md
writeLines(readme_lines, "README.md")

### Generate index.html
# List all immediate directories at the root
dirs <- list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
dirs <- dirs[dirs != ""]  # Remove empty entries

# Start writing the HTML content
html_lines <- c(
  "<!DOCTYPE html>",
  "<html>",
  "<head>",
  "  <meta charset='UTF-8'>",
  "  <title>Project Directory Index</title>",
  "</head>",
  "<body>",
  "  <h1>Project Directory Index</h1>",
  "  <p>Welcome! This repository contains the following directories:</p>",
  "  <ul>"
)

# Add a list item with links for each directory
dir_links <- paste0("    <li><a href='./", dirs, "/'>", dirs, "/</a></li>")
html_lines <- c(html_lines, dir_links)

# Close HTML tags
html_lines <- c(
  html_lines,
  "  </ul>",
  "  <hr>",
  "  <p>Auto-generated by R.</p>",
  "</body>",
  "</html>"
)

# Write to index.html
writeLines(html_lines, "index.html")

